/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSkillRouteImport } from './routes/_app/skill'
import { Route as AppAboutRouteImport } from './routes/_app/about'
import { Route as AppBlogIndexRouteImport } from './routes/_app/blog/index'
import { Route as AppBlogSlugRouteImport } from './routes/_app/blog/$slug'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSkillRoute = AppSkillRouteImport.update({
  id: '/skill',
  path: '/skill',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBlogIndexRoute = AppBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBlogSlugRoute = AppBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/about': typeof AppAboutRoute
  '/skill': typeof AppSkillRoute
  '/blog/$slug': typeof AppBlogSlugRoute
  '/blog/': typeof AppBlogIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof AppAboutRoute
  '/skill': typeof AppSkillRoute
  '/': typeof AppIndexRoute
  '/blog/$slug': typeof AppBlogSlugRoute
  '/blog': typeof AppBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/about': typeof AppAboutRoute
  '/_app/skill': typeof AppSkillRoute
  '/_app/': typeof AppIndexRoute
  '/_app/blog/$slug': typeof AppBlogSlugRoute
  '/_app/blog/': typeof AppBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/skill' | '/blog/$slug' | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/skill' | '/' | '/blog/$slug' | '/blog'
  id:
    | '__root__'
    | '/_app'
    | '/_app/about'
    | '/_app/skill'
    | '/_app/'
    | '/_app/blog/$slug'
    | '/_app/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/skill': {
      id: '/_app/skill'
      path: '/skill'
      fullPath: '/skill'
      preLoaderRoute: typeof AppSkillRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/about': {
      id: '/_app/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/blog/': {
      id: '/_app/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof AppBlogIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/blog/$slug': {
      id: '/_app/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof AppBlogSlugRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppAboutRoute: typeof AppAboutRoute
  AppSkillRoute: typeof AppSkillRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBlogSlugRoute: typeof AppBlogSlugRoute
  AppBlogIndexRoute: typeof AppBlogIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAboutRoute: AppAboutRoute,
  AppSkillRoute: AppSkillRoute,
  AppIndexRoute: AppIndexRoute,
  AppBlogSlugRoute: AppBlogSlugRoute,
  AppBlogIndexRoute: AppBlogIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
